---
homebrew_user: james
homebrew_group: staff

homebrew_taps_personal:
  - supersonic-app/supersonic

homebrew_installed_packages_personal:
  - 1password-cli
  - entr
  - exiftool
  - flyctl
  - hugo
  - imagemagick
  - mise
  - tea
  - wireguard-go
  - wireguard-tools

homebrew_cask_apps_personal:
  - adobe-creative-cloud
  - beardedspice
  - discord
  - drivedx
  - gpxsee
  - jettison
  - karabiner-elements
  - llm
  - lyx
  - macs-fan-control
  - mactex
  - microsoft-teams
  - orbstack
  - plexamp
  - plex
  - qmk-toolbox
  - rar
  - spotify
  - steam
  - supersonic
  - tex-live-utility
  - tunnelblick

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: false
